DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  telescopeName TEXT UNIQUE NOT NULL,
  indiServer TEXT NOT NULL,
  indiPort TEXT NOT NULL
);


